# Generated by Django 5.1.7 on 2025-04-18 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_dailyjournal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('last_checkin_date', models.DateField(blank=True, null=True)),
                ('total_check_ins', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='achievementrule',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='dailyjournal',
            name='user',
        ),
        migrations.DeleteModel(
            name='MotivationalMessage',
        ),
        migrations.AlterModelOptions(
            name='achievementlog',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='achievementlog',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddField(
            model_name='achievement',
            name='condition',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AddField(
            model_name='achievementlog',
            name='date_awarded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='priority',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='objective',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='pendente', max_length=50),
        ),
        migrations.DeleteModel(
            name='AchievementRule',
        ),
        migrations.DeleteModel(
            name='DailyJournal',
        ),
        migrations.RemoveField(
            model_name='achievementlog',
            name='created_at',
        ),
    ]
