# Generated by Django 5.1.7 on 2025-06-15 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0005_rename_date_diary_datetime'),
        ('progress', '0003_userprogress_remove_achievementrule_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='description',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='name',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='status',
        ),
        migrations.AddField(
            model_name='objective',
            name='activity',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='mental_health.activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objective',
            name='deadline',
            field=models.DateField(blank=True),
        ),
    ]
