# Generated by Django 5.1.7 on 2025-06-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_remove_objective_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='period',
            field=models.CharField(choices=[('1w', '1 semana'), ('2w', '2 semanas'), ('3w', '3 semanas')], default='1w', max_length=2),
        ),
    ]
