# Generated by Django 5.1.7 on 2025-04-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physical_health.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'Exercise Log',
                'verbose_name_plural': 'Exercise Logs',
            },
        ),
        migrations.CreateModel(
            name='Hydration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('goal_achieved', models.BooleanField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'Hydration',
                'verbose_name_plural': 'Hydration',
            },
        ),
        migrations.CreateModel(
            name='PhysicalCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_level', models.IntegerField()),
                ('sleep_quality', models.CharField(choices=[('Ruim', 'Ruim'), ('Medio', 'Medio'), ('Bom', 'Bom')], max_length=50)),
                ('healthy_eating', models.CharField(max_length=50)),
                ('activity_level', models.IntegerField()),
                ('is_pain', models.BooleanField()),
                ('is_smoked', models.BooleanField()),
                ('is_alcohol', models.BooleanField()),
                ('checkin_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'Physical Check-In',
                'verbose_name_plural': 'Physical Check-Ins',
            },
        ),
        migrations.CreateModel(
            name='PhysicalSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('pain_level', models.IntegerField()),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physical_health.physicalcheckin')),
            ],
            options={
                'verbose_name': 'Physical Symptom',
                'verbose_name_plural': 'Physical Symptons',
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField()),
                ('goal_achieved', models.BooleanField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'Exercise Log',
                'verbose_name_plural': 'Exercise Logs',
            },
        ),
    ]
