# Generated by Django 5.1.7 on 2025-04-04 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalcheckin',
            name='healthy_eating',
            field=models.CharField(choices=[('Ruim', 'Ruim'), ('Medio', 'Medio'), ('Bom', 'Bom')], max_length=50),
        ),
        migrations.CreateModel(
            name='PhysicalJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='physical_health.physicalcheckin')),
            ],
        ),
        migrations.DeleteModel(
            name='PhysicalSymptom',
        ),
    ]
