# Generated by Django 5.1.7 on 2025-04-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_health', '0003_remove_physicalcheckin_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydration',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
