# Generated by Django 5.1.7 on 2025-04-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_health', '0004_alter_hydration_date_alter_steps_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalcheckin',
            old_name='is_alcohol',
            new_name='is_took_medicine',
        ),
        migrations.RenameField(
            model_name='physicalcheckin',
            old_name='is_smoked',
            new_name='is_used_screen_too_much',
        ),
        migrations.RemoveField(
            model_name='physicalcheckin',
            name='height',
        ),
        migrations.RemoveField(
            model_name='physicalcheckin',
            name='score',
        ),
        migrations.RemoveField(
            model_name='physicalcheckin',
            name='weight',
        ),
        migrations.DeleteModel(
            name='PhysicalRecommendation',
        ),
    ]
