# Generated by Django 5.1.7 on 2025-04-21 19:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_health', '0005_rename_is_alcohol_physicalcheckin_is_took_medicine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hydration',
            new_name='HydrationLog',
        ),
        migrations.RenameModel(
            old_name='Steps',
            new_name='StepsLog',
        ),
    ]
