# Generated by Django 5.1.7 on 2025-04-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_health', '0006_rename_hydration_hydrationlog_rename_steps_stepslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalcheckin',
            name='healthy_eating',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Boa', 'Boa'), ('Regular', 'Regular'), ('Ruim', 'Ruim'), ('Pessimo', 'Pessimo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='physicalcheckin',
            name='sleep_quality',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Boa', 'Boa'), ('Regular', 'Regular'), ('Ruim', 'Ruim'), ('Pessimo', 'Pessimo')], max_length=50),
        ),
    ]
