# Generated by Django 5.1.7 on 2025-04-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_health', '0007_alter_physicalcheckin_healthy_eating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalcheckin',
            name='healthy_eating',
            field=models.CharField(choices=[('excelente', 'Excelente'), ('boa', 'Boa'), ('regular', 'Regular'), ('ruim', 'Ruim'), ('pessimo', 'Pessimo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='physicalcheckin',
            name='sleep_quality',
            field=models.CharField(choices=[('excelente', 'Excelente'), ('boa', 'Boa'), ('regular', 'Regular'), ('ruim', 'Ruim'), ('pessimo', 'Pessimo')], max_length=50),
        ),
    ]
