# Generated by Django 5.1.7 on 2025-04-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_health', '0008_alter_physicalcheckin_healthy_eating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Força', 'Força'), ('Flexibilidade', 'Flexibilidade'), ('Aeróbico', 'Aeróbico'), ('Resistência', 'Resistência')], max_length=100),
        ),
    ]
