# Generated by Django 5.1.7 on 2025-05-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_health', '0009_alter_exercise_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='rating',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('Díficil', 'Díficil'), ('Intermediário', 'Intermediário'), ('Fácil', 'Fácil')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
