# Generated by Django 5.1.7 on 2025-06-08 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_health', '0010_remove_exerciselog_rating_alter_exercise_difficulty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhysicalCheckin',
        ),
    ]
