# Generated by Django 5.1.7 on 2025-06-10 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_health', '0011_delete_physicalcheckin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciselog',
            options={'verbose_name': 'Registro de Exercircio', 'verbose_name_plural': 'Registros de Exercircio'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hydrationlog',
            name='goal_achieved',
        ),
        migrations.RemoveField(
            model_name='stepslog',
            name='goal_achieved',
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_distance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='duration',
            field=models.PositiveIntegerField(default=111111111),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Força', 'Força'), ('Flexibilidade', 'Flexibilidade'), ('Aeróbico', 'Aeróbico'), ('Resistência', 'Resistência')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hydrationlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hydrationlog',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
