# Generated by Django 5.1.7 on 2025-06-10 23:25

import apps.physical_health.models.hydratation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_health', '0012_alter_exerciselog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrationlog',
            name='date',
            field=models.DateField(default=apps.physical_health.models.hydratation.HydrationLog.today),
        ),
    ]
