import { StyleSheet, } from "react-native"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E6E6FA",
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: "center",
    paddingVertical: 40,
  },
  logoContainer: {
    marginBottom: 20,
    alignItems: "center",
  },
  logo: {
    width: 280,
    height: 60,
  },
  card: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    width: '90%',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  nameRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  inputContainerHalf: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 15,
    height: 50,
    width: "48%",
    backgroundColor: "white",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 15,
    height: 50,
    backgroundColor: "white",
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: "#1F2937",
    fontFamily: "Poppins-Regular",
  },
  placeholder: {
    color: "#9CA3AF",
  },
  rowContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dropdownContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    paddingLeft: 10,
  },
  photoContainer: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderStyle: "dashed",
    borderRadius: 10,
    padding: 20,
    alignItems: "center",
    marginVertical: 10,
  },
  photoPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  photoText: {
    fontSize: 18,
    color: "#9C5DE4",
    fontWeight: "600",
    marginBottom: 5,
    fontFamily: "Poppins-SemiBold",
  },
  photoSubtext: {
    fontSize: 14,
    color: "#6B7280",
    fontFamily: "Poppins-Regular",
  },
  button: {
    backgroundColor: "#9C5DE4",
    borderRadius: 100,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  buttonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
  },
  loginContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 20,
  },
  loginText: {
    fontSize: 16,
    color: "#4B5563",
    fontFamily: "Poppins-Regular",
  },
  loginLink: {
    fontSize: 16,
    color: "#9C5DE4",
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
  },
  footerContainer: {
    marginTop: 30,
    alignItems: "center",
  },
  footerText: {
    fontSize: 18,
    color: "#6B7280",
    textAlign: "center",
    fontFamily: "Poppins-Medium",
  },
  demoButton: {
    marginTop: 15,
    padding: 10,
    alignItems: "center",
  },
  demoButtonText: {
    fontSize: 14,
    color: "#9C5DE4",
    fontFamily: "Poppins-Medium",
  },
  eyeIcon: {
    padding: 5,
  },
})
