import { colors } from "@/styles/colors";
import { spacing } from "@/styles/spacing";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  scrollView: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: spacing.lg,
    backgroundColor: colors.background.main,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginBottom: spacing.md,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  headerIcon: {
    width: 24,
    height: 24,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#000",
  },
  notificationContainer: {
    position: "relative",
  },
  notificationBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#FF3B30",
  },
  quoteCard: {
    backgroundColor: "#B8CEFF",
    margin: 16,
    padding: 24,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  quoteText: {
    fontSize: 20,
    color: "#000",
    textAlign: "center",
    fontWeight: "600",
  },
  checkInCard: {
    backgroundColor: "white",
    margin: 16,
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionCard: {
    backgroundColor: "white",
    margin: 16,
    marginTop: 8,
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#6366F1",
  },
  lastCheckIn: {
    color: "#9CA3AF",
    fontSize: 14,
    marginBottom: 16,
  },
  levelContainer: {
    marginBottom: 16,
  },
  levelLabel: {
    color: "#4B5563",
    fontSize: 14,
    marginBottom: 8,
  },
  levelRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  progressBar: {
    flex: 1,
    height: 8,
    backgroundColor: "#E5E7EB",
    borderRadius: 4,
    marginHorizontal: 8,
  },
  progress: {
    height: "100%",
    borderRadius: 4,
  },
  levelNumber: {
    color: "#9CA3AF",
    fontSize: 12,
    width: 16,
    textAlign: "center",
  },
  statusContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginVertical: 8,
  },
  statusItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 24,
  },
  statusIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  statusIconText: {
    fontSize: 16,
  },
  medicationIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  medicationIconText: {
    fontSize: 16,
  },
  painIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#10B981",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  normalUseIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  normalUseIconText: {
    fontSize: 16,
  },
  statusText: {
    color: "#4B5563",
    fontSize: 14,
  },
  blueText: {
    color: "#3B82F6",
  },
  noteContainer: {
    backgroundColor: "#F9FAFB",
    padding: 12,
    borderRadius: 8,
    marginVertical: 12,
  },
  noteText: {
    color: "#4B5563",
    fontSize: 14,
    fontStyle: "italic",
  },
  dateText: {
    color: "#9CA3AF",
    fontSize: 14,
    marginBottom: 16,
  },
  detailsButton: {
    backgroundColor: "#E0E7FF",
    padding: 15,
    borderRadius: 100,
    alignItems: "center",
  },
  detailsButtonText: {
    color: "#6366F1",
    fontWeight: "500",
    fontSize: 16,
  },
  checkInButton: {
    backgroundColor: "#818CF8",
    margin: 16,
    padding: 15,
    borderRadius: 100,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  checkIcon: {
    marginRight: 8,
  },
  checkInButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "500",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1F2937",
  },
  hydrationInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  currentValue: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1F2937",
  },
  goalValue: {
    fontSize: 16,
    color: "#6B7280",
  },
  progressBarWide: {
    height: 12,
    backgroundColor: "#E5E7EB",
    borderRadius: 6,
    marginBottom: 16,
  },
  progressFill: {
    height: "100%",
    borderRadius: 6,
  },
  registerButton: {
    backgroundColor: "#93C5FD",
    padding: 15,
    borderRadius: 100,
    alignItems: "center",
  },
  registerButtonText: {
    color: "#FFFFFF",
    fontWeight: "500",
    fontSize: 16,
  },
  stepsInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  motivationalText: {
    color: "#84CC16",
    fontSize: 14,
    marginTop: 8,
  },
  exercisesSection: {
    margin: 16,
    marginTop: 8,
    marginBottom: 32,
  },
  filterIcon: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  filterIconText: {
    fontSize: 18,
  },
  exerciseCarousel: {
    marginBottom: 12,
  },
  exerciseCard: {
    backgroundColor: "white",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    padding: 16,
    marginRight: 16,
    width: 320,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  exerciseContent: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  exerciseIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  exerciseIconText: {
    fontSize: 20,
  },
  exerciseDetails: {
    flex: 1,
    marginHorizontal: 12,
  },
  exerciseName: {
    fontSize: 16,
    fontWeight: "500",
    color: "#1F2937",
    marginBottom: 4,
  },
  exerciseTime: {
    color: "#6B7280",
    fontSize: 14,
  },
  startExerciseButton: {
    backgroundColor: "#60A5FA",
    padding: 15,
    borderRadius: 100,
    alignItems: "center",
  },
  startExerciseText: {
    color: "#FFFFFF",
    fontWeight: "500",
    fontSize: 16,
  },
  paginationContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#D1D5DB",
    marginHorizontal: 4,
  },
  paginationDotActive: {
    backgroundColor: "#60A5FA",
    width: 12,
    height: 12,
    borderRadius: 6,
  },
})
