# Generated by Django 5.1.7 on 2025-04-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mindfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Mindfulness',
                'verbose_name_plural': 'Mindfulness',
            },
        ),
        migrations.CreateModel(
            name='MindfulnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mindfulness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_health.mindfulness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'Mindfulness Log',
                'verbose_name_plural': 'Mindfulness Logs',
            },
        ),
        migrations.CreateModel(
            name='WellnessCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('mood_intensity', models.IntegerField()),
                ('stress_level', models.IntegerField()),
                ('anxiety_level', models.IntegerField()),
                ('score', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'Wellness Check-In',
                'verbose_name_plural': 'Wellness Check-ins',
            },
        ),
        migrations.CreateModel(
            name='EmotionalJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_health.wellnesscheckin')),
            ],
            options={
                'verbose_name': 'Emotional Journal',
                'verbose_name_plural': 'Emotional Journals',
            },
        ),
    ]
