# Generated by Django 5.1.7 on 2025-06-10 01:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Mindfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Respiração Consciente', 'Respiração Consciente'), ('Meditação Mindfulness', 'Meditação Mindfulness'), ('Consciência Emocional', 'Consciência Emocional'), ('Atenção nas Atividades', 'Atenção nas Atividades')], max_length=22)),
            ],
            options={
                'verbose_name': 'Mindfulness',
                'verbose_name_plural': 'Mindfulness',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('mood', models.CharField(choices=[('Excelente', 'Excelente'), ('Bom', 'Bom'), ('Neutro', 'Neutro'), ('Ruim', 'Ruim'), ('Péssimo', 'Péssimo')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='diary/photos/')),
                ('activities', models.ManyToManyField(blank=True, to='mental_health.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diário',
                'verbose_name_plural': 'Diários',
            },
        ),
        migrations.CreateModel(
            name='MindfulnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=200)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('mindfulness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_health.mindfulness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mindfulness Log',
                'verbose_name_plural': 'Mindfulness Logs',
            },
        ),
    ]
