# Generated by Django 5.1.7 on 2025-06-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0002_alter_diary_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diary',
            unique_together=set(),
        ),
    ]
