# Generated by Django 5.1.7 on 2025-04-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0002_remove_wellnesscheckin_user_mindfulnesslog_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalcheckin',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
