# Generated by Django 5.1.7 on 2025-06-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0003_rename_date_diary_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='datetime',
            new_name='date',
        ),
    ]
