# Generated by Django 5.1.7 on 2025-04-22 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0004_diary_delete_mentalrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalcheckin',
            name='mood',
            field=models.CharField(choices=[('Muito Feliz', 'Muito Feliz'), ('Feliz', 'Feliz'), ('Neutro', 'Neutro'), ('Triste', 'Triste'), ('Muito Triste', 'Muito Triste')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mentalcheckin',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
