# Generated by Django 5.1.7 on 2025-06-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0004_rename_datetime_diary_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='date',
            new_name='datetime',
        ),
    ]
