# Generated by Django 5.1.7 on 2025-04-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0005_alter_mentalcheckin_mood_alter_mentalcheckin_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentalcheckin',
            name='score',
        ),
    ]
