# Generated by Django 5.1.7 on 2025-04-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0006_remove_mentalcheckin_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
