# Generated by Django 5.1.7 on 2025-04-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0007_alter_diary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindfulness',
            name='type',
            field=models.CharField(choices=[('Foco na Respiração', 'Foco na Respiração'), ('Escaneamento Corporal', 'Escaneamento Corporal'), ('Em Movimento', 'Em Movimento'), ('Pensamentos e Emoções', 'Pensamentos e Emoções')], max_length=100),
        ),
    ]
