# Generated by Django 5.1.7 on 2025-05-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0008_alter_mindfulness_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mindfulnesslog',
            name='rating',
        ),
        migrations.AlterField(
            model_name='mindfulness',
            name='difficulty',
            field=models.CharField(choices=[('Díficil', 'Díficil'), ('Intermediário', 'Intermediário'), ('Fácil', 'Fácil')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mindfulness',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
